# Generated by Django 3.2.22 on 2023-12-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('ID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('NAME', models.TextField(null=True)),
                ('COST', models.IntegerField(null=True)),
                ('QTY', models.IntegerField(null=True)),
                ('NOTE', models.TextField(null=True)),
            ],
            options={
                'db_table': 'consumables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('ID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('NAME', models.TextField(null=True)),
                ('GENDER', models.TextField(null=True)),
                ('DOB', models.DateField(null=True)),
                ('ADDRESS', models.TextField(null=True)),
                ('PHONE_NUMBER', models.CharField(max_length=15, null=True)),
                ('NOTE', models.TextField(null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TIME', models.DateTimeField(auto_now_add=True, null=True)),
                ('NOTE', models.TextField(null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('ID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('NAME', models.TextField(null=True)),
                ('PRICE', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('DISCOUNT', models.IntegerField(null=True)),
                ('NOTE', models.TextField(null=True)),
                ('ORDER', models.ForeignKey(db_column='ORDER', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.orders')),
                ('SERVICE', models.ForeignKey(db_column='SERVICE', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.services')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
